version: '3.1'

services:

  db:
    image: mariadb
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    ports:
      - 3306:3306
    volumes:
      - ./fgAPIServer:/docker-entrypoint-initdb.d
